// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUGZCQ7Y4YFKdMPqCpOyQvxQ1ZGnTf3o0',
    appId: '1:638857518734:web:f724af1e89b8ac58bd33df',
    messagingSenderId: '638857518734',
    projectId: 'smart-quiz-f6a9a',
    authDomain: 'smart-quiz-f6a9a.firebaseapp.com',
    storageBucket: 'smart-quiz-f6a9a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR8WHd26C5F7SLhoMEIz38MpfADITz6ko',
    appId: '1:638857518734:android:67da8f95586f3ff0bd33df',
    messagingSenderId: '638857518734',
    projectId: 'smart-quiz-f6a9a',
    storageBucket: 'smart-quiz-f6a9a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkThmOICHdfENI9G7VwEN0ONal4Cy4fx4',
    appId: '1:638857518734:ios:1d48f2f77d7f3f69bd33df',
    messagingSenderId: '638857518734',
    projectId: 'smart-quiz-f6a9a',
    storageBucket: 'smart-quiz-f6a9a.firebasestorage.app',
    iosBundleId: 'com.example.smartQuiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkThmOICHdfENI9G7VwEN0ONal4Cy4fx4',
    appId: '1:638857518734:ios:1d48f2f77d7f3f69bd33df',
    messagingSenderId: '638857518734',
    projectId: 'smart-quiz-f6a9a',
    storageBucket: 'smart-quiz-f6a9a.firebasestorage.app',
    iosBundleId: 'com.example.smartQuiz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUGZCQ7Y4YFKdMPqCpOyQvxQ1ZGnTf3o0',
    appId: '1:638857518734:web:233b578b36e0c7f1bd33df',
    messagingSenderId: '638857518734',
    projectId: 'smart-quiz-f6a9a',
    authDomain: 'smart-quiz-f6a9a.firebaseapp.com',
    storageBucket: 'smart-quiz-f6a9a.firebasestorage.app',
  );
}
